# Generated by Django 5.1.4 on 2026-05-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_path', models.CharField(max_length=512)),
                ('reason', models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('spam', 'Spam'), ('impersonation', 'Impersonation'), ('illegal_content', 'Illegal content'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action taken')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('short_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='links.shorturl')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_abuse_status_created'), models.Index(fields=['short_url', 'status'], name='idx_abuse_url_status')],
            },
        ),
    ]
